## Model Notebook for Coding in SK-LEARN

In [1]:
#import libaraies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression

In [3]:
# Load dataset
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
#Seprate the features(x) and labels/target(y)
x = df[['total_bill']]          # x is alawys be doble dimension
y= df['tip']

In [9]:
# train test split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8)


In [21]:
 # Preprocess the data
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [22]:
x_train

array([[ 2.40702007],
       [-0.48442015],
       [ 1.16911172],
       [ 1.19823898],
       [-0.93589261],
       [-0.90900591],
       [-0.55163689],
       [ 0.14629695],
       [-1.25405186],
       [ 0.51150792],
       [ 0.83750913],
       [-0.3802342 ],
       [ 0.10596691],
       [-0.20323011],
       [-0.66030396],
       [ 1.63514781],
       [-1.04904079],
       [ 0.8016602 ],
       [-0.5460355 ],
       [ 0.11828998],
       [ 1.47046679],
       [-1.27197632],
       [-0.36679085],
       [ 0.282971  ],
       [-0.0699169 ],
       [-0.71967875],
       [-0.25140211],
       [ 2.05749301],
       [-1.02999605],
       [-0.34998666],
       [ 0.48798206],
       [ 0.042111  ],
       [-1.07928832],
       [-0.63901866],
       [ 2.13143142],
       [-1.11177642],
       [-0.19986927],
       [-1.2249246 ],
       [ 0.08356133],
       [ 2.29275161],
       [ 0.08804244],
       [ 0.54735685],
       [ 0.44541146],
       [ 2.33532221],
       [ 2.75542685],
       [-1

In [23]:
# call the model
model = LinearRegression()

# train the model
model.fit(x_train,y_train)

LinearRegression()

In [24]:
# Prediction
y_pred = model.predict(x_test)


In [25]:
model.predict([[30]])       ## For checking

array([28.60017157])

In [26]:
y_pred

array([3.00981591, 2.97053965, 4.39823173, 2.64061906, 4.44045371,
       2.14377436, 2.11824479, 2.40005196, 1.96703118, 2.42459962,
       3.2042334 , 3.92986232, 4.49642238, 2.78790503, 5.21125033,
       2.23116404, 2.29106033, 2.80852507, 2.9941054 , 3.25332873,
       4.15962844, 2.81539842, 3.33580887, 5.96731835, 2.53064553,
       2.12610004, 2.72702683, 2.54930175, 2.2704403 , 1.99256075,
       3.57146644, 2.33426422, 2.30480703, 3.08935034, 2.40397958,
       2.59545136, 1.98666931, 3.40454233, 1.9542664 , 3.91709753,
       3.09720559, 2.29302415, 2.58072276, 2.54733794, 2.74961068,
       2.88707759, 2.59741517, 3.26903923, 2.91948051])

In [27]:
y_test

33      2.45
21      2.75
85      5.17
37      3.07
11      5.00
147     1.63
232     3.39
177     2.00
82      1.83
74      2.20
241     2.00
210     2.00
238     4.67
13      3.00
197     5.00
209     2.23
26      2.00
146     1.36
204     4.00
183     6.50
47      6.00
200     4.00
230     2.00
170    10.00
171     3.16
120     2.31
25      2.34
138     2.00
139     2.75
136     2.00
57      1.50
163     2.00
199     2.00
160     3.50
127     2.00
205     3.23
10      1.71
88      5.85
53      1.56
116     5.07
15      3.92
158     2.61
93      4.30
84      2.03
49      3.00
80      3.00
159     2.00
181     5.65
154     2.00
Name: tip, dtype: float64

In [29]:
# Evaluate the model
from sklearn.metrics import mean_squared_error, r2_score
print('MSE: ', mean_squared_error(y_test, y_pred))
print('R2: ', r2_score(y_test, y_pred))

MSE:  1.4339505103079944
R2:  0.48422404648241646


### `Save and load the Model`

In [35]:
# save the model
import pickle
pickle.dump(model, open('model_01.pkl', 'wb'))      # wb= writting binary

In [37]:
# Load the model
import pickle
model_load = pickle.load(open('model_01.pkl', 'rb'))    # rb = read binaray

In [38]:
model_load.predict([[15]])

array([15.77659861])